config/routes.rb
Rails.application.routes.draw do
  resources :prospects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :prospect
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  has_many :conversations
  belongs_to :user


  validates :first_name, :last_name, :phone, :status, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :prospects
end

# Phone regex
# ^(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[-.]?\d{3}[-.]?\d{4}$

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_prospect
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET prospects/1/conversations
  def index
    @conversations = @prospect.conversations
  end

  # GET prospects/1/conversations/1
  def show
  end

  # GET prospects/1/conversations/new
  def new
    @conversation = @prospect.conversations.build
  end

  # GET prospects/1/conversations/1/edit
  def edit
  end

  # POST prospects/1/conversations
  def create
    @conversation = @prospect.conversations.build(conversation_params)

    if @conversation.save
      redirect_to([@conversation.prospect, @conversation], notice: 'Conversation was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT prospects/1/conversations/1
  def update
    if @conversation.update_attributes(conversation_params)
      redirect_to([@conversation.prospect, @conversation], notice: 'Conversation was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE prospects/1/conversations/1
  def destroy
    @conversation.destroy

    redirect_to prospect_conversations_url(@prospect)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:prospect_id])
    end

    def set_conversation
      @conversation = @prospect.conversations.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def conversation_params
      params.require(:conversation).permit(:chat, :prospect_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def homepage
    
  end

end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prospect, only: %i[ show edit update destroy ]

  # GET /prospects or /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1 or /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
    # @prospect = current_user.prospects.build
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects or /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)
    @prospect.user = current_user

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to prospect_url(@prospect), notice: "Prospect was successfully created." }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1 or /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to prospect_url(@prospect), notice: "Prospect was successfully updated." }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1 or /prospects/1.json
  def destroy
    @prospect.destroy

    respond_to do |format|
      format.html { redirect_to prospects_url, notice: "Prospect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = current_user.prospects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prospect_params
      params.require(:prospect).permit(:first_name, :last_name, :phone, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/conversations/_form.html.erb
<%= form_for([@conversation.prospect, @conversation]) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chat %><br />
    <%= f.text_area :chat %>
  </div>
  <div class="field">
    <%= f.label :prospect %><br />
    <%= f.text_field :prospect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', [@conversation.prospect, @conversation] %> |
<%= link_to 'Back', prospect_conversations_path(@conversation.prospect) %>

app/views/conversations/index.html.erb
<h1>Listing conversations</h1>

<table>
  <tr>
    <th>Chat</th>
    <th>Prospect</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conversations.each do |conversation| %>
  <tr>
    <td><%= conversation.chat %></td>
    <td><%= conversation.prospect %></td>
    <td><%= link_to 'Show', [conversation.prospect, conversation] %></td>
    <td><%= link_to 'Edit', edit_prospect_conversation_path(conversation.prospect, conversation) %></td>
    <td><%= link_to 'Destroy', [conversation.prospect, conversation], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conversation', new_prospect_conversation_path(params[:prospect_id]) %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', prospect_conversations_path(@conversation.prospect) %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Chat:</b>
  <%= @conversation.chat %>
</p>

<p>
  <b>Prospect:</b>
  <%= @conversation.prospect %>
</p>


<%= link_to 'Edit', edit_prospect_conversation_path(@conversation.prospect, @conversation) %> |
<%= link_to 'Back', prospect_conversations_path(@conversation.prospect) %>

app/views/home/homepage.html.erb
<h1>homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmTd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/prospects/_form.html.erb
<%= form_with(model: prospect) do |form| %>
  <% if prospect.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
        <% prospect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <%# <div>
    <%= form.label :user_id, style: "display: block" %>
    <%# <%= form.text_field :user_id %>
  <%# </div> %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prospects/_prospect.html.erb
<div id="<%= dom_id prospect %>">

  <%# <td><%= prospect.email </td> %>
  <td><%= prospect.first_name + " " + prospect.last_name%></td>
  <td><%= prospect.phone %></td>
  <td><%= prospect.status %></td>
  <td><%= current_user.email %></td>
  <td><%= prospect.user.email %></td>
  <td class="text-center">
    <div class="between">
      <%= link_to prospect do %>
        <button class="btn btn-outline-primary btn-sm show-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Mostrar">
          <i class="bi bi-eye"></i>
        </button>
      <% end %>

      <%= link_to edit_prospect_path(prospect) do %>
        <button class="btn btn-outline-primary btn-sm edit-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Editar">
          <i class="bi bi-pencil"></i>
        </button>
      <% end %>

      <%= link_to prospect, method: :delete, data: {turbo_method: :delete, turbo_confirm: "¿Está seguro de eliminarlo?"} do %>
        <button class="btn btn-outline-primary btn-sm del-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Eliminar">
          <i class="bi bi-trash"></i>
        </button>
      <% end %>
    
    </div>
  </td>

</div>

app/views/prospects/edit.html.erb
<h1>Editing prospect</h1>

<%= render "form", prospect: @prospect %>

<br>

<div>
  <%= link_to "Show this prospect", @prospect %> |
  <%= link_to "Back to prospects", prospects_path %>
</div>

app/views/prospects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Prospectos</h1>
<br>

<%= link_to new_prospect_path, class:"text-decoration-none btn btn-outline-light text-light hover-btn mx-auto" do %>
  <i class="bi bi-blockquote-left">&emsp;Nuevo Prospecto</i>
<% end %>

<h5 class="text-light">Total de <%= Prospect.count %> prospectos.</h5>
<div id="prospects">
<div class="scroll-tbl-prospects">
  <table class="table table-primary table-hover border border-primary mb-3 pb-2" id="prospects-tbl">
    <thead>
      <tr class="table-info">
        <th scope="col">Email</th>
        <th scope="col">Nombre</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Estatus</th>
        <th scope="col">Ingresado por</th>
        <th scope="col">Fecha ingreso</th>
        <th scope="col">Conversaciones</th>
        <th scope="col" class="text-center" id="index_options_col">
          Opciones
        </th>
      </tr>
    </thead>

    <tbody>
      <% @prospects.each do |prospect| %>
        <tr>
          <%= render prospect %>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/prospects/new.html.erb
<h1>New prospect</h1>

<%= render "form", prospect: @prospect %>

<br>

<div>
  <%= link_to "Back to prospects", prospects_path %>
</div>

app/views/prospects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prospect %>

<div>
  <%= link_to "Edit this prospect", edit_prospect_path(@prospect) %> |
  <%= link_to "Back to prospects", prospects_path %>

  <%= button_to "Destroy this prospect", @prospect, method: :delete %>
</div>

app/views/shared/_footer.html.erb
    <footer id="footer" class="text-white">
      <h5>&copy Du </h5>
      <h6 class="small">MMXXII</h6>
    </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <div class="container-fluid">
    <%= link_to image_tag('D_48.png'), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', root_path, class: "navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Prospectos', prospects_path, class: "navbar-brand" %>
        </li>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
      </ul>
      <form class="d-flex">
        
        <% if current_user %>
        <%# <% if user_signed_in? %> %>
          <%= current_user %>   
          <p>Hola 
            <%= current_user.email %>
            <%= current_user.email.split('@')[0] %>
     
            /
            <%= link_to 'Salir', destroy_user_session_path, 'data-turbo-method': :delete, class:"ms-1" %>
            <%# <%= link_to 'Cuenta', edit_registration_path, class:"ms-1" %>
          </p>
            <%# <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
        <% else %>
          <p>
            <%= link_to 'Ingresar', new_user_session_path %> / 
          </p>
        <% end %>
        
      </form>
    </div>
  </div>
</nav>